### **TENSORS**

In [11]:
import torch
import numpy as np

In [12]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-0.5733, -0.1606,  0.4670, -1.2019],
        [ 0.3414, -2.9827,  0.7687, -0.1105],
        [-1.1435,  0.6206, -0.6960, -0.2814]])

In [13]:
tensor_3d = torch.randn(2,3,4)
tensor_3d

tensor([[[ 0.6227,  0.9142,  0.7097,  0.7137],
         [ 0.0905,  0.9281,  1.9694,  0.4242],
         [ 1.2251,  0.7161, -0.8169,  0.3646]],

        [[-0.3034, -1.8771, -1.1248, -2.1088],
         [ 0.1301, -0.3143, -0.1816,  1.3859],
         [ 2.4001, -0.8973,  0.4060, -0.0290]]])

_Numpy <-> Tensors_

In [14]:
np_arr = np.random.rand(2,3)
np_arr

array([[0.99111262, 0.69174337, 0.81382855],
       [0.67481895, 0.71105314, 0.31995589]])

In [15]:
tensor_np = torch.tensor(np_arr)
tensor_np

tensor([[0.9911, 0.6917, 0.8138],
        [0.6748, 0.7111, 0.3200]])

#### **TENSOR OPERATIONS**

In [16]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

_Reshape and view_

In [17]:
my_torch.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [18]:
my_torch.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

_Slicing_

In [19]:
# Grabing a specific element
my_torch[2]

tensor(2)

In [20]:
# Grab a slice
my_torch[2:7]

tensor([2, 3, 4, 5, 6])

#### **TENSOR MATH OPERATIONS**

In [21]:
a = torch.tensor([1,2,3,4])
b = torch.tensor([5,6,7,8])

_Addition_

In [29]:
print(a+b)
print(torch.add(a,b))
print(a.add(b))

tensor([ 6,  8, 10, 12])
tensor([ 6,  8, 10, 12])
tensor([ 6,  8, 10, 12])


_Subtraction_

In [31]:
print(b-a)
print(torch.sub(b,a))
print(b.sub(a))

tensor([4, 4, 4, 4])
tensor([4, 4, 4, 4])
tensor([4, 4, 4, 4])


_Multiplication_

In [32]:
print(a*b)
print(torch.mul(a,b))
print(a.mul(b))

tensor([ 5, 12, 21, 32])
tensor([ 5, 12, 21, 32])
tensor([ 5, 12, 21, 32])


_Division_

In [33]:
print(a/b)
print(torch.div(a,b))
print(a.div(b))

tensor([0.2000, 0.3333, 0.4286, 0.5000])
tensor([0.2000, 0.3333, 0.4286, 0.5000])
tensor([0.2000, 0.3333, 0.4286, 0.5000])


_Modulus or Remainder_

In [35]:
print(torch.remainder(b,a))
print(b.remainder(a))

tensor([0, 0, 1, 0])
tensor([0, 0, 1, 0])


_Exponent or Power_

In [36]:
print(torch.pow(a,b))
print(a.pow(b))

tensor([    1,    64,  2187, 65536])
tensor([    1,    64,  2187, 65536])
